name: Build and Release n8nctl

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write # Required for creating releases

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - id: vars
        name: Set binary name
        run: echo "binary_name=n8nctl-${{ matrix.goos }}-${{ matrix.goarch }}" >> $GITHUB_OUTPUT

      - name: Build CLI
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -o dist/${{ steps.vars.outputs.binary_name }} .

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Upload binaries and checksums
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
